# Generated by Django 5.0.3 on 2024-04-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resultdata",
            old_name="price",
            new_name="max_spend",
        ),
        migrations.AddField(
            model_name="resultdata",
            name="min_spend",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
