# Generated by Django 5.0.3 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_resultdata_day_of_travel_resultdata_query_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="querydata",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="resultdata",
            name="location",
            field=models.CharField(max_length=200),
        ),
    ]
