# Generated by Django 5.0.3 on 2024-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_querydata_location_alter_resultdata_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="querydata",
            name="criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resultdata",
            name="time_of_day",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
